

//Anomen party reaction
IF
	Global("MRAnomenReaction","GLOBAL",0) 
	Global("ImoenRomanceActive","GLOBAL",1)
	Global("MRSleptImoen","GLOBAL",1)
	IsValidForPartyDialog("Imoen2")
	IsValidForPartyDialog("Anomen")
	GlobalTimerExpired("MRPartyReactionTimer","GLOBAL")
THEN
	RESPONSE #100
	SetGlobal("MRAnomenReaction","GLOBAL",1) 
	SetGlobalTimer("MRPartyReactionTimer","GLOBAL",ONE_DAY)
	StartDialogueNoSet(Player1)
END