
//Cernd party reaction
IF
	Global("MRCerndReaction","GLOBAL",0)
	Global("ImoenRomanceActive","GLOBAL",2)
	Global("MRSleptImoen","GLOBAL",1)
	IsValidForPartyDialog("Imoen2")
	IsValidForPartyDialog("Cernd")
	GlobalTimerExpired("MRPartyReactionTimer","GLOBAL")
THEN
	RESPONSE #100
	SetGlobal("MRCerndReaction","GLOBAL",1) 
	SetGlobalTimer("MRPartyReactionTimer","GLOBAL",ONE_DAY)
	StartDialogueNoSet(Player1)
END