//Anomen scripting

IF
RealGlobalTimerExpired("MRDreamComAnomenTimer","GLOBAL")
InParty("Anomen")
See(Player1)
!ActuallyInCombat()
!StateCheck(Player1,CD_STATE_NOTVALID)
!StateCheck(Myself,CD_STATE_NOTVALID)
AreaType(DUNGEON)
Global("MRAnomenBanterFire","GLOBAL", 0)
!GlobalGT("Chapter","GLOBAL",%bg2_chapter_3%)
!Global("MRDreamRomanceComment","GLOBAL",1)
THEN
RESPONSE #100
SetGlobal("MRAnomenBanterFire","GLOBAL", 2)
StartDialogNoSet(Player1)
END