IF
	True()
THEN
	RESPONSE #100
	CutSceneId("BoyFemMR")
	MoveToPoint([4698.2284])
END

IF
	True()
THEN
	RESPONSE #100
	CutSceneId("GirlMr")
	MoveToPoint([4771.2172])
END

IF
	True()
THEN
	RESPONSE #100
	CutSceneId(Player1)
	Wait(10)
	MoveViewObject("ImDream",6)
	Wait(1)
	SetGlobal("MRDream1","GLOBAL",5)
	ActionOverride("GoblinMR",DestroySelf())
	ActionOverride("ImDream",StartDialogNoSet(Player1))
	EndCutSceneMode()
END

