
//Lathander stonghold talk
IF
	Global("MRStrongholdTalkCler","GLOBAL",0)
	!StateCheck(Player1,CD_STATE_NOTVALID)
    AreaCheckObject("AR0902","Imoen2")
	AreaCheckObject("AR0902",Player1)
	GlobalGT("JoinLathander","GLOBAL",0)
	InParty("Imoen2")
	!ActuallyInCombat()
THEN
	RESPONSE #100
	SetGlobal("MRStrongholdTalkCler","GLOBAL",1)
	ActionOverride("Imoen2",StartDialogueNoSet(Player1))
END