
//fighter stonghold talk
IF
	Global("MRStrongholdTalkFigh","GLOBAL",0)
	!StateCheck(Player1,CD_STATE_NOTVALID)
    
	GlobalGT("PCKeepOwner","GLOBAL",0)
	InParty("Imoen2")
	!ActuallyInCombat()
	AreaCheckObject("AR1306","Imoen2")
	AreaCheckObject("AR1306",Player1)
THEN
	RESPONSE #100
	SetGlobal("MRStrongholdTalkFigh","GLOBAL",1)
	ActionOverride("Imoen2",StartDialogueNoSet(Player1))
END