IF
  True()
THEN
  RESPONSE #100
    CutSceneId("Imoen2")  // 
    MoveToPointNoInterrupt([2138.1400])
    FaceObject("MRWOMER")
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)  // 
    MoveViewObject("MRWOMER",FAST)
    MoveToPointNoInterrupt([2194.1380])
    FaceObject("MRWOMER")
    Wait(6)
    SetGlobal("MRRingSellImoen","GLOBAL",3)
    ActionOverride("MRWOMER",StartDialogNoSet(Player1))
    EndCutSceneMode()
END

