@echo off
cd override
oggdec MRIMDRE1.ogg
oggdec MRIMDRE2.ogg
oggdec MRImInt1.ogg
oggdec MRImInt2.ogg
oggdec MRImInt3.ogg
oggdec MRImNig1.ogg
oggdec MRImNig2.ogg
oggdec MRImEndG.ogg
oggdec MRImRom1.ogg
oggdec MRImRom2.ogg
oggdec MRImRom3.ogg
oggdec MRImRom4.ogg
oggdec MRImRom5.ogg
oggdec MRImRom6.ogg
oggdec IRAerie.ogg
oggdec IRDawn.ogg
oggdec IRDusk.ogg
oggdec IRSadRom.ogg
oggdec IRShort.ogg
oggdec IRYayRom.ogg
del MRIm*.ogg
del IR*.ogg
del oggdec.exe