cd override
oggdec MRImDre1.ogg
oggdec MRImDre2.ogg
oggdec MRImInt1.ogg
oggdec MRImInt2.ogg
oggdec MRImInt3.ogg
oggdec MRImEndG.ogg
oggdec MRImRom1.ogg
oggdec MRImRom2.ogg
oggdec MRImRom3.ogg
oggdec MRImRom4.ogg
oggdec MRImRom5.ogg
oggdec MRImRom6.ogg
oggdec IRAerie.ogg
oggdec IRDawn.ogg
oggdec IRDusk.ogg
oggdec IRSadRom.ogg
oggdec IRShort.ogg
oggdec IRYayRom.ogg
rm MRIm*.ogg
rm IR*.ogg
rm oggdec
rm oggdec.exe
